import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from 'next/font/google';

export const metadata: Metadata = {
  title: "IndieHires",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700']
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {children}
      </body>
    </html>
  );
}
